[tool.black]
line-length = 79
exclude = '''
(
    ^/\..*
  | ^/src/
  | ^/github2pypi/
)
'''

[build-system]
requires = [
    "setuptools>=42",
    "scikit-build>=0.13",
    "cmake>=3.18",
    "cython",
    "numpy"
]
build-backend = "setuptools.build_meta"
